export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_DOCTORS_PENDING = 'REQUEST_DOCTORS_PENDING'; 
export const REQUEST_DOCTORS_SUCCESS = 'REQUEST_DOCTORS_SUCCESS'; 
export const REQUEST_DOCTORS_FAILED = 'REQUEST_DOCTORS_FAILED'; 